server:
  port: 8080
spring:
  application:
    name: api-gateway
  profiles:
  - dev
  cloud:
    gateway:
      routes:
      - id: products
        uri: lb://PRODUCTS
        predicates:
        - Path=/product/**
      - id: cart
        uri: lb://CART
        predicates:
        - Path=/cart/**
  session:
    store-type: redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password: