server:
  port: 8082
spring:
  profiles: dev
  application:
    name: cart
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  datasource:
    url: jdbc:h2:mem:cartdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
